dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  dbCreate: update
  username: root
  password: 'j3 s8 1r0nm@n'

environments:
  development:
    dataSource:
      dbCreate: update
      url: "jdbc:mysql://localhost/quincaillerie?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"